#!/bin/sh
set -e

if [ "$1" = 'configure' ]; then
    update-initramfs -u
    if ! grep -Eq '^(.*\s)?ip=' /proc/cmdline; then
        cat <<-EOT
			OpenSSH has been added to the initramfs. Don't forget to check
			your "ip=" kernel bootparameter to match your desired initramfs
			ip configuration.

		EOT
    fi
fi

#DEBHELPER#
exit 0
