#!/bin/sh

PREREQ=""

prereqs() {
	echo "$PREREQ"
}

case "$1" in
	prereqs)
		prereqs
		exit 0
	;;
esac

. /scripts/functions

[ -s /run/sshd.pid ] || exit 0

log_begin_msg "Stopping OpenSSH"

pid=$(cat /run/sshd.pid)
ps -eo ppid,pid | sed -nr "s/^\s*$pid\s+([0-9]+)\s*$/\1/p" | xargs -r kill
kill $pid
